---

- name: Add the Nginx source to the APT source list
  apt_repository: repo="ppa:nginx/stable" state=present

- name: Install all required packages
  package:
    name: "{{item}}"
    state: present
  with_items:
   - nginx
   - nginx-extras
   - openssl
   - python-pip

- name: Install docker python module
  pip:
    name: "docker-compose==1.12.0"
